# Generated by Codex on 2026-09-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleprofile",
            name="primary_operator",
            field=models.ForeignKey(
                blank=True,
                help_text="UI-owned operator responsible for confirmation-required occurrences.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_schedule_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
