# Generated by Django 6.1.1 on 2026-09-11 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_scheduleprofile_primary_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprofile',
            name='backup_operator',
            field=models.ForeignKey(blank=True, help_text='Preferred confirmation cover when the primary operator is unavailable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_schedule_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleprofile',
            name='expected_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RunbookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.PositiveIntegerField()),
                ('report_date', models.DateField()),
                ('step_index', models.PositiveIntegerField()),
                ('step_text', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule_id', 'report_date', 'step_index'), name='unique_report_runbook_step')],
            },
        ),
    ]
