# Generated by Codex on 2026-09-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveScheduleCoverage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("schedule_id", models.PositiveIntegerField()),
                ("schedule_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_leave_schedule_coverages", to=settings.AUTH_USER_MODEL)),
                ("covering_admin", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leave_schedule_coverages", to=settings.AUTH_USER_MODEL)),
                ("leave_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedule_coverages", to="leave.leaverequest")),
            ],
            options={"ordering": ["schedule_name"]},
        ),
        migrations.AddConstraint(
            model_name="leaveschedulecoverage",
            constraint=models.UniqueConstraint(fields=("leave_request", "schedule_id"), name="unique_leave_schedule_coverage"),
        ),
    ]
