"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import django
from project_paths import project_path

try:
    from dotenv import load_dotenv
except ImportError:  # Environment variables remain sufficient for locked-down office hosts.
    def load_dotenv(*_args, **_kwargs):
        return False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def _env_flag(name: str, default: bool = False) -> bool:
    return os.environ.get(name, "1" if default else "0").strip().lower() in {
        "1", "true", "yes", "on",
    }
SCHEDULER_PROJECT_PATH = project_path(os.getenv("SCHEDULER_PROJECT_PATH"), BASE_DIR.parent / "scheduler_project")


SCHEDULER_MASTER_PATH = project_path(os.getenv("SCHEDULER_MASTER_PATH"),
                                     SCHEDULER_PROJECT_PATH / "file_repository" / "Schedule_Master.json")

SCHEDULER_STATE_DB_PATH = project_path(os.getenv("SCHEDULER_STATE_DB_PATH"), SCHEDULER_PROJECT_PATH / "scheduler.db")


# Scheduler control plane.  The background scheduler starts this local API;
# the Django UI sends it monitoring reads and operator control intents.  In
# production set an unguessable SCHEDULER_API_TOKEN and keep the API on a
# private network.  A read-only local fallback is opt-in for UI-only local
# inspection before the background worker is launched.
SCHEDULER_API_BASE_URL = os.environ.get("SCHEDULER_API_BASE_URL", "http://127.0.0.1:8091")
SCHEDULER_API_TOKEN = os.environ.get("SCHEDULER_API_TOKEN", "")
SCHEDULER_API_TIMEOUT_SECONDS = int(os.environ.get("SCHEDULER_API_TIMEOUT_SECONDS", "3"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# A predictable fallback is allowed only for an out-of-the-box localhost
# demonstration; production refuses to start without a supplied key.
DEBUG = _env_flag("DJANGO_DEBUG", True)
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError("DJANGO_SECRET_KEY must be configured when DJANGO_DEBUG=0.")
    SECRET_KEY = "django-insecure-local-demo-only-change-before-production"

SCHEDULER_ALLOW_LOCAL_READ_FALLBACK = os.environ.get(
    "SCHEDULER_ALLOW_LOCAL_READ_FALLBACK", "0"
).strip().lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [
    item.strip()
    for item in os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if item.strip()
]

# Turn these on only when the approved reverse proxy exposes HTTPS.  They are
# intentionally configuration-driven because ITRP deployments commonly use an
# internal TLS terminator rather than Django's development server.
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = _env_flag("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_flag("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)
SECURE_SSL_REDIRECT = _env_flag("DJANGO_SECURE_SSL_REDIRECT", False)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "apps.audit",  # Its runserver command keeps staticfiles and manages audit delivery.
    'django.contrib.staticfiles',
    'apps.accounts',
    "apps.tasks",
    "apps.leave",
    "apps.scheduler",
    "apps.dashboard",
    "apps.sulog",
    "apps.eloadlog",
    "apps.mailer",
]
AUTH_USER_MODEL = "accounts.AdminUser"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "dashboard:home"
LOGOUT_REDIRECT_URL = "accounts:login"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "builtins": ["apps.dashboard.templatetags.indian_dates"],
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.audit.context_processors.audit_delivery_health",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

PORTAL_DATABASE_PATH = project_path(os.getenv("DJANGO_DATABASE_PATH"), BASE_DIR / "db.sqlite3")
PORTAL_DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PORTAL_DATABASE_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

if django.VERSION >= (6, 1):
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
