-- Oracle input/mirror schema for the Python SBI scheduler.
--
-- Run as the owner of the scheduler tables. It is idempotent for the standard
-- table names below: existing application data is preserved, and the
-- additional SOURCE_RECORD_ID / RESULT_COUNT mirror columns are added only
-- when absent. Do not put Oracle credentials in this file.
--
-- The Python worker reads Schedule Master, DATEMAST, and HOLIDAY_MASTER. It
-- may mirror local Schedule_extg statuses to SCHEDULE_EXTG when
-- SCHEDULER_EXTG_MIRROR=1. Local Python state remains authoritative.

DECLARE
    PROCEDURE ensure_table(p_ddl IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_ddl;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN -- name already used
                RAISE;
            END IF;
    END;

    PROCEDURE ensure_column(
        p_table_name IN VARCHAR2,
        p_column_name IN VARCHAR2,
        p_definition IN VARCHAR2
    ) IS
        l_exists NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO l_exists
          FROM user_tab_columns
         WHERE table_name = UPPER(p_table_name)
           AND column_name = UPPER(p_column_name);

        IF l_exists = 0 THEN
            EXECUTE IMMEDIATE
                'ALTER TABLE ' || DBMS_ASSERT.SQL_OBJECT_NAME(p_table_name)
                || ' ADD (' || DBMS_ASSERT.SIMPLE_SQL_NAME(p_column_name)
                || ' ' || p_definition || ')';
        END IF;
    END;
BEGIN
    -- Authoritative configuration. RUN_CONFIG is a CLOB JSON object, for
    -- example {"RUNS_ON":["DAILY"],"RUN_BY":{"FROM_TIME":"06:00","TO_TIME":"06:30"}}.
    ensure_table(q'[
        CREATE TABLE SCHEDULE_EXTRACT_MASTER (
            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                CONSTRAINT PK_SCHEDULE_EXTRACT_MASTER PRIMARY KEY,
            NAME VARCHAR2(100) NOT NULL,
            PACKAGE_NAME VARCHAR2(500) NOT NULL,
            RUN_CONFIG CLOB DEFAULT '{}',
            MARGIN VARCHAR2(12) DEFAULT 'T',
            SAME_DAY NUMBER(1) DEFAULT 0 NOT NULL,
            TIME_FLAG NUMBER(1) DEFAULT 0 NOT NULL,
            IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
            CONFIRMATION_NEEDED NUMBER(1) DEFAULT 0 NOT NULL,
            CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
            CONSTRAINT CHK_SEM_SAME_DAY CHECK (SAME_DAY IN (0, 1)),
            CONSTRAINT CHK_SEM_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
        )
    ]');
    ensure_column('SCHEDULE_EXTRACT_MASTER', 'RUN_CONFIG', 'CLOB');
    ensure_column('SCHEDULE_EXTRACT_MASTER', 'MARGIN', 'VARCHAR2(12) DEFAULT ''T''');
    ensure_column('SCHEDULE_EXTRACT_MASTER', 'SAME_DAY', 'NUMBER(1) DEFAULT 0');
    ensure_column('SCHEDULE_EXTRACT_MASTER', 'TIME_FLAG', 'NUMBER(1) DEFAULT 0');
    ensure_column('SCHEDULE_EXTRACT_MASTER', 'IS_ACTIVE', 'NUMBER(1) DEFAULT 1');
    ensure_column('SCHEDULE_EXTRACT_MASTER', 'CONFIRMATION_NEEDED', 'NUMBER(1) DEFAULT 0');
    ensure_column('SCHEDULE_EXTRACT_MASTER', 'CREATED_DATE', 'TIMESTAMP DEFAULT SYSTIMESTAMP');

    -- DATEMAST is the authority for available report dates. Existing
    -- enterprise rows are untouched.
    ensure_table(q'[
        CREATE TABLE DATEMAST (
            REPORT_DATE DATE CONSTRAINT PK_DATEMAST PRIMARY KEY
        )
    ]');
    ensure_column('DATEMAST', 'REPORT_DATE', 'DATE');

    -- Only actual bank holidays belong here; Saturday/Sunday are handled by
    -- the Python working-day rules.
    ensure_table(q'[
        CREATE TABLE HOLIDAY_MASTER (
            HOLIDAY_DATE DATE CONSTRAINT PK_HOLIDAY_MASTER PRIMARY KEY,
            HOLIDAY_NAME VARCHAR2(200)
        )
    ]');
    ensure_column('HOLIDAY_MASTER', 'HOLIDAY_DATE', 'DATE');

    -- Oracle mirror of local execution-facing staging status. The local JSON
    -- ID is SOURCE_RECORD_ID, which makes manual NULL-report-date runs
    -- idempotent too.
    ensure_table(q'[
        CREATE TABLE SCHEDULE_EXTG (
            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                CONSTRAINT PK_SCHEDULE_EXTG PRIMARY KEY,
            SOURCE_RECORD_ID NUMBER,
            REPORT_DATE DATE,
            NAME VARCHAR2(100) NOT NULL,
            STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
            SAME_DAY NUMBER(1) DEFAULT 0,
            RUN_DATE TIMESTAMP,
            ERROR_INFO CLOB,
            RESULT_COUNT NUMBER,
            UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            CONSTRAINT CHK_S_EXTG_STATUS
                CHECK (STATUS IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED')),
            CONSTRAINT CHK_S_EXTG_SAME_DAY CHECK (SAME_DAY IN (0, 1))
        )
    ]');
    ensure_column('SCHEDULE_EXTG', 'SOURCE_RECORD_ID', 'NUMBER');
    ensure_column('SCHEDULE_EXTG', 'RESULT_COUNT', 'NUMBER');
    ensure_column('SCHEDULE_EXTG', 'UPDATED_AT', 'TIMESTAMP DEFAULT SYSTIMESTAMP');
END;
/

-- The original PL/SQL-only version used this exact status constraint name and
-- did not allow RUNNING. Replace it safely so the mirror reflects each state.
-- If your existing status constraint has a different name, align it once with
-- these four values before enabling SCHEDULER_EXTG_MIRROR.
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SCHEDULE_EXTG DROP CONSTRAINT CHK_S_EXTG_STATUS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN -- constraint does not exist
            RAISE;
        END IF;
END;
/

ALTER TABLE SCHEDULE_EXTG ADD CONSTRAINT CHK_S_EXTG_STATUS
    CHECK (STATUS IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED'));
/

DECLARE
    PROCEDURE ensure_index(p_ddl IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_ddl;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
BEGIN
    ensure_index(
        'CREATE UNIQUE INDEX UQ_S_EXTG_SOURCE_RECORD ON SCHEDULE_EXTG (SOURCE_RECORD_ID)'
    );
    ensure_index(
        'CREATE INDEX IX_S_EXTG_STATUS_REPORT ON SCHEDULE_EXTG (STATUS, REPORT_DATE)'
    );
END;
/

-- Expected least-privilege grants (replace SCHEDULER_RUNTIME with the
-- approved runtime account):
-- GRANT SELECT ON SCHEDULE_EXTRACT_MASTER TO SCHEDULER_RUNTIME;
-- GRANT SELECT ON DATEMAST TO SCHEDULER_RUNTIME;
-- GRANT SELECT ON HOLIDAY_MASTER TO SCHEDULER_RUNTIME;
-- GRANT SELECT, INSERT, UPDATE ON SCHEDULE_EXTG TO SCHEDULER_RUNTIME;
